### ISSUE TITLE
[Error 13] Toolkit Error: Provided OutputNode/InputNode name does not exist or does not match with one contained in model file Provided: out:0

### ISSUE THREAD

**Issue by ludlows** [ardamavi/Intel-Movidius-NCS-Keras#7]
[Error 13] Toolkit Error: Provided OutputNode/InputNode name does not exist or does not match with one contained in model file Provided: out:0

Hi,

I am not sure why I encounter this error, since "out" is the name of output layer.

Thanks

**Comment by yungshenglu** [comment]
Can you provide your code? :)
